### ISSUE TITLE
`process` is not available in the browser

### ISSUE THREAD

**Issue by veekeys** [iTwin/auth-clients#241] opened 2024-05-06 20:09 UTC
<img width="564" alt="image" src="https://github.com/iTwin/auth-clients/assets/81580355/6154e85b-a566-46fa-a526-bd72e3493ddb">

Getting this with the newest `@itwin/browser-authorization` version. Probably, should not rely on environment variables for the resolution of authority...

**Comment by ben-polinsky** [comment] 2024-05-06 20:19
Thanks. 

This is due to our earlier reliance on webpack/cra magic and has not been caught as the `getImsAuthority` method is only called as a fallback.

**Comment by ben-polinsky** [comment] 2024-05-08 22:03
@veekeys Could you test out the fix in `v1.1.1`?

**Comment by ben-polinsky** [comment] 2024-05-09 17:29
Closing, please let us know if the issue is not resolved.

**Closed by ben-polinsky** 2024-05-09 17:29 UTC
Labels: bug

**Comment by veekeys** [comment] 2024-05-10 08:58
@ben-polinsky Sorry, checked now, seems that error is gone.
Thanks!

**Comment by ben-polinsky** [comment] 2024-05-10 13:25
np! Thanks for testing.
